Better status handling for renovate jenkins trigger

diff --git a/.github/workflows/renovate-jenkins-trigger.yml b/.github/workflows/renovate-jenkins-trigger.yml
--- a/.github/workflows/renovate-jenkins-trigger.yml
+++ b/.github/workflows/renovate-jenkins-trigger.yml
@@ -64,25 +64,34 @@ jobs:
             if [[ "$QUEUE_ITEM_STATUS" == "false" ]]; then
               # The job has left the queue, query the job's URL for its status
               JOB_URL=$(curl -s "$JENKINS_URL/queue/item/$QUEUE_NUMBER/api/json" | jq -r '.executable.url')
-              JOB_STATUS=$(curl -s "$JOB_URL/api/json" | jq -r '.result')
-            
-              echo "Job status is $JOB_STATUS"
-              if [[ "$JOB_STATUS" == "FAILURE" || "$JOB_STATUS" == "UNSTABLE" ]]; then
-                echo "Jenkins job has failed."
-                echo "See more $JOB_URL"
-                exit 1
-              elif [[ "$JOB_STATUS" == "SUCCESS" ]]; then
-                echo "Jenkins job has succeeded."
-                echo "See more $JOB_URL"
-                exit 0
-              elif [[ "$JOB_STATUS" == "null" ]]; then
-                echo "Jenkins job is still running..."
-                sleep 30  # Sleep for 30 seconds before checking again
+              JOB_RESPONSE=$(curl -s "$JOB_URL/api/json" | jq -r '{ result: .result, is_building: .building }')
+              JOB_STATUS=$(echo "$JOB_RESPONSE" | jq -r '.result')
+              IS_JOB_BUILDING=$(echo "$JOB_RESPONSE" | jq -r '.is_building')
+
+              echo "Job status is $JOB_RESPONSE"
+
+              if [[ "$IS_JOB_BUILDING" == "false" ]]; then
+                if [[ "$JOB_STATUS" == "FAILURE" || "$JOB_STATUS" == "UNSTABLE" ]]; then
+                  echo "Jenkins job has failed."
+                  echo "See more $JOB_URL"
+                  exit 1
+                elif [[ "$JOB_STATUS" == "SUCCESS" ]]; then
+                  echo "Jenkins job has succeeded."
+                  echo "See more $JOB_URL"
+                  exit 0
+                elif [[ "$JOB_STATUS" == "null" ]]; then
+                  echo "Something went wrong, Jenkins job is in null status"
+                  echo "See more $JOB_URL"
+                  exit 1
+                else
+                  echo "Jenkins job is in an unknown state $JOB_STATUS"
+                  echo "See more $JOB_URL"
+                  exit 1
+                fi
               else
-                echo "Jenkins job is in an unknown state $JOB_STATUS"
-                echo "See more $JOB_URL"
-                exit 1
-              fi
+                echo "Job is still running"
+                sleep 30  # Sleep for 30 seconds before checking again
+              fi  
             else
               echo "Job is still in the queue..."
               sleep 30
