More changes to renovate-jenkins-trigger
* Use environment variables (set output is deprecated)
* Add validation for queue number + logging
* HTTP_RESPONSE_STATUS make sure the first one is taken
* Fix logging issues and comment debug logs out

diff --git a/.github/workflows/renovate-jenkins-trigger.yml b/.github/workflows/renovate-jenkins-trigger.yml
--- a/.github/workflows/renovate-jenkins-trigger.yml
+++ b/.github/workflows/renovate-jenkins-trigger.yml
@@ -23,7 +23,7 @@ jobs:
         id: extract_branch
         run: |
           BRANCH_NAME=$(jq -r '.pull_request.head.ref' $GITHUB_EVENT_PATH)
-          echo "::set-output name=branch::$BRANCH_NAME"
+          echo "branch=$BRANCH_NAME" >> "$GITHUB_ENV"
 
       - name: Trigger Jenkins Job
         id: trigger_jenkins
@@ -35,36 +35,43 @@ jobs:
 
           # Extract the queue number from the response headers
           QUEUE_NUMBER=$(echo "$RESPONSE_HEADERS" | grep -i "^location:" | tr -d '\r' | sed -E 's#^.*/queue/item/([0-9]+)/?#\1#')
+          
+          # Check if QUEUE_NUMBER is a valid number
+          if ! [[ "$QUEUE_NUMBER" =~ ^[0-9]+$ ]]; then
+            echo "ERROR: Failed to extract a valid queue number. Got: '$QUEUE_NUMBER'"
+            echo "DEBUG: Full response headers:"
+            echo "$RESPONSE_HEADERS"
+            exit 1
+          fi
 
           # Set QUEUE_NUMBER as an output variable
-          echo "::set-output name=queue_number::$QUEUE_NUMBER"
+          echo "queue_number=$QUEUE_NUMBER" >> "$GITHUB_ENV"
 
           # Extract the HTTP response status code
-          HTTP_RESPONSE_STATUS=$(echo "$RESPONSE_HEADERS" | grep -i "HTTP/" | awk '{print $2}')
+          HTTP_RESPONSE_STATUS=$(echo "$RESPONSE_HEADERS" | grep -i "HTTP/" | head -n 1 | awk '{print $2}')
 
           echo "Jenkins job queued with queue number: $QUEUE_NUMBER"
           echo "HTTP Response Status: $HTTP_RESPONSE_STATUS"
 
           if [[ "$HTTP_RESPONSE_STATUS" -ne 201 ]]; then
-            echo "Failed to trigger Jenkins job. HTTP Response Code: HTTP_RESPONSE_STATUS"
+            echo "Failed to trigger Jenkins job. HTTP Response Code: $HTTP_RESPONSE_STATUS"
             exit 1
           fi
 
       - name: Check Jenkins Job Status
         id: check_jenkins_job
         run: |
-          BRANCH_NAME="${{ steps.extract_branch.outputs.branch }}"
+          BRANCH_NAME="${{ env.branch }}"
 
           # Access the queue_number output from the previous step
-          QUEUE_NUMBER="${{ steps.trigger_jenkins.outputs.queue_number }}"
+          QUEUE_NUMBER="${{ env.queue_number }}"
 
           while true; do
             QUEUE_ITEM_STATUS=$(curl -s "$JENKINS_URL/queue/item/$QUEUE_NUMBER/api/json" | jq -r '.blocked')
-            echo "DEBUG: Queue number: $QUEUE_NUMBER"
-            echo "DEBUG: Jenkins status request - $JENKINS_URL/queue/item/$QUEUE_NUMBER/api/json"
-            echo "DEBUG: Queue response - $(curl -s "$JENKINS_URL/queue/item/$QUEUE_NUMBER/api/json")"
-            echo "DEBUG: Blocked status - $QUEUE_ITEM_STATUS"
-
+            # echo "DEBUG: Queue number: $QUEUE_NUMBER"
+            # echo "DEBUG: Jenkins status request - $JENKINS_URL/queue/item/$QUEUE_NUMBER/api/json"
+            # echo "DEBUG: Queue response - $(curl -s "$JENKINS_URL/queue/item/$QUEUE_NUMBER/api/json")"
+            # echo "DEBUG: Blocked status - $QUEUE_ITEM_STATUS"
 
             if [[ "$QUEUE_ITEM_STATUS" == false ]]; then
               # The job has left the queue, query the job's URL for its status
